sudo: required
dist: trusty

services:
  - docker

language: node_js
matrix:
  include:
  - node_js: "7.6"

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.yarn-cache

notifications:
  email: false

before_install:
  # Fix a problem with apt-get failing later, see http://docs.travis-ci.com/user/installing-dependencies/#Installing-Ubuntu-packages
  - sudo apt-get update -qq
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get update
  - sudo apt-get install --force-yes --yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev

script:
  - docker run -d --name vnc -p 5911:5901 -e "VNC_PW=my-new-password" consol/centos-xfce-vnc
  - docker ru:n --link vnc:vnc -e CHECK_PORT=5911 -e CHECK_HOST=vnc giorgos/takis
  - node --version
  - yarn --version
  - yarn test
