sudo: required
dist: trusty

services:
  - docker

language: node_js
matrix:
  include:
  - node_js: "7.6"

cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.yarn-cache

notifications:
  email: false

script:
  - docker run -d --name vnc -p 5911:5901 -e "VNC_PW=my-new-password" consol/centos-xfce-vnc
  - docker ru:n --link vnc:vnc -e CHECK_PORT=5911 -e CHECK_HOST=vnc giorgos/takis
  - node --version
  - yarn --version
  - yarn test
